"""add reliability_score to vendors

Revision ID: bccee615e31a
Revises: 6020efa92caf
Create Date: 2026-03-26 19:22:03.310427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bccee615e31a'
down_revision = '6020efa92caf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('category', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_invoices_category'), 'invoices', ['category'], unique=False)
    op.add_column('vendors', sa.Column('reliability_score', sa.Numeric(precision=5, scale=2), nullable=False, server_default='100.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'reliability_score')
    op.drop_index(op.f('ix_invoices_category'), table_name='invoices')
    op.drop_column('invoices', 'category')
    # ### end Alembic commands ###
